<?php

	// Start Session
	require_once '../../php/startSession.php';

	// If not signed in, just redirect to the login page
	require_once '../../../lib/etc/adminHeaderRedirect.php';
	adminHeaderRedirect('../', '../');

	require_once '../../../lib/adminUIRender.php';
	$adminUIRender = new adminUIRender();

	echo $adminUIRender->renderAdminHtmlTop('../../', 'Customers');

	echo $adminUIRender->renderAdminUIMenuToggleScripts('../../');

?>

</head>

<body>
	<div class="cmsBodyWrapper">

		<?php
			echo $adminUIRender->renderAdminTopBar('../../');
		?>

		<?php
			echo $adminUIRender->renderAdminSideBar('../../');
		?>

		<div class="cmsMainContentWrapper styledText textColorThemeCustomers">
			<div style="margin-left: 2em; margin-right: 2em;" class="spacedText">
				<h1>Customers</h1>
			</div>

			<br>

			<div class="twoColPage-Content-Info">
				<div id="twoColContentWrapper" class="paddingLeftRight90">
					<?php

						require_once '../../../lib/render/customer/customerTable.php';

						$customerTable = new customerTable();

						$customerTable->rootPathPrefix = '../';
						$customerTable->queryParams = 'ORDER BY nameIndex DESC';

						if (isset($_GET['p']) && is_numeric($_GET['p'])) {
							$customerTable->page = (int)$_GET['p'];
						}

						$customerTable->render();

						echo $customerTable->output;

					?>
				</div>

				<div id="twoColInfoWrapper" class="paddingLeftRight90">
				
					<div class="grayInfoBox defaultMainShadows desktopOnlyBlock">
						<h3>Did you know?</h3>
						
						<br>

						<!-- Will put a random did you know message here generated by php at some point -->
						<p>With UltiScape, you can add tags to each customer to sort them into relevant categories.</p>
					</div>

					<br><hr><br>

					<h3 style="color: var(--grayTextColorTheme);">Other Links</h3>

					<br>

					<a style="color: var(--grayTextColorTheme); display: inline-block;" href="./import">Import</a> | <a style="color: var(--grayTextColorTheme); display: inline-block;" href="./export">Export</a>

				</div>
			</div>
			<br>
		</div>
		
		<?php 
			echo $adminUIRender->renderAdminFooter('../../');
		?>

		<?php 
			echo $adminUIRender->renderAdminMobileNavBar('../../');
		?>

	</div>

	<?php
		echo $adminUIRender->renderAdminTopBarDropdowns('../../');
	?>
</body>

<?php 
	echo $adminUIRender->renderAdminHtmlBottom('../../');
?>
